### ISSUE TITLE
yii\base\ErrorException: fseek(): stream does not support seeking

### ISSUE THREAD

**Issue by Saboteur777** [vaersaagod/dospaces#17]
Trying to download an asset through the Control Panel with the download button on Asset edit page, getting an internal server error with the following stack trace: 

```
2020-08-24 12:16:57 [-][1][sculjoq6uhh6cl0sdpk1bjhk55][error][yii\base\ErrorException:2] yii\base\ErrorException: fseek(): stream does not support seeking in /var/www/vendor/yiisoft/yii2/web/Response.php:586
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /var/www/vendor/yiisoft/yii2/web/Response.php(586): fseek()
#3 /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php(1077): yii\web\Response->sendStreamAsFile()
#4 [internal function]: craft\controllers\AssetsController->actionDownloadAsset()
#5 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#7 /var/www/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#8 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#9 /var/www/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#10 /var/www/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#11 /var/www/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#13 /var/www/web/index.php(21): yii\base\Application->run()
#14 {main}
```

**Comment by aelvan** [comment]
Fixed in 1.1.3.
